<?php
$config["menu"]["type"] = array (
	1 => "meat",
	2 => "vege",
	3 => "soap",
);
$config["menu"]["meat"] = array (
	array (
	    "id"=>"1",
	    "foodname"=>"荷兰豆炒香肠",
	    "price"=>"16",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/helan_lacang720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/helan_lacang400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36397488848",
	),
	array (
	    "id"=>"2",
	    "foodname"=>"土豆烧鸡块",
	    "price"=>"13",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/tudou_chicken720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/tudou_chicken400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36397348653",
	),
	array (
	    "id"=>"3",
	    "foodname"=>"芹菜香干肉丝",
	    "price"=>"12",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/qincai_rousi720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/qincai_rousi400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36389863563",
	),
	array (
	    "id"=>"4",
	    "foodname"=>"香菇鸡片",
	    "price"=>"12",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/xianggu_ji720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/xianggu_ji400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36387786699",
	),
	array (
	    "id"=>"5",
	    "foodname"=>"茭白肉片",
	    "price"=>"12",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/jiaobai_rou720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/jiaobai_rou400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36397260838",
	),
	array (
	    "id"=>"6",
	    "foodname"=>"番茄土豆炖牛腩",
	    "price"=>"22",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/fanqie_niu720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/fanqie_niu400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36379274407",
	),
);
$config["menu"]["vege"] = array (
	array (
	    "id"=>"1",
	    "foodname"=>"酸辣土豆丝",
	    "price"=>"8",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/suanla_tudou720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/suanla_tudou400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36387550556",
	),
	array (
	    "id"=>"2",
	    "foodname"=>"爆炒双花",
	    "price"=>"10",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/baochao_two720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/baochao_two400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36397336248",
	),
	array (
	    "id"=>"3",
	    "foodname"=>"手撕包心菜",
	    "price"=>"10",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/shousi_xin720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/shousi_xin400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36387562260",
	),
	array (
	    "id"=>"4",
	    "foodname"=>"番茄炒蛋",
	    "price"=>"9",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/fanqie_dan720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/fanqie_dan400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36387502190",
	),
	array (
	    "id"=>"5",
	    "foodname"=>"地三鲜",
	    "price"=>"10",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/three_xian720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/three_xian400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36389951498",
	),
);
$config["menu"]["soap"] = array (
	array (
	    "id"=>"1",
	    "foodname"=>"排骨藕汤",
	    "price"=>"14",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/paigu_soap720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/paigu_soap400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36397524525",
	),
	array (
	    "id"=>"2",
	    "foodname"=>"玉米排骨汤",
	    "price"=>"14",
	    "weight"=>"2",
	    "main"=>"",
	    "extra"=>"",
	    "todo"=>"",
	    "img"=>"http://pages.qiehaole.com/food/yumi_soap720.jpg",
	    "thumb"=>"http://pages.qiehaole.com/food/yumi_soap400.jpg",
	    "link"=>"http://item.taobao.com/item.htm?id=36389575998",
	),
);
